@startuml

class View{
- JTextArea

+ handleEvent()
+ runUI()
+ showSaveOptions()
+ showFileChooser()
+ showErrorMessage()
+ insertText(text)
+ getText()
}

class Controller{
+ initialize()
}

class Model{
+ checkFileStatus()
+ saveToFile(text)
+ setCurrFilePath(path)
+ loadFromFile(path)
}
@enduml