@startuml
title save file as
participant "user" as u
participant "app" as a
u -> a : handleEvent(save file as)
a -> u : askUserForSaveLocation()
u -> a : fileSelected
a -> a : setFilePath(path)
a -> a : saveToFile(text)
@enduml