@startuml
title save file as (design)
participant View as v
participant Controller as c
participant Model as m
v -> c : handleEvent(save file as)
c -> v : askForSaveLocation()
v -> c : fileSelected
c -> m : setFilePath()
c -> m : saveToFile()
@enduml